language: php

php:
    - 7.1
    - 7.0
    - 5.6
    - 5.5
    - 5.4
    - 5.3

cache:
    directories:
        - $HOME/.composer/cache

install:
    - composer install

script:
    - vendor/bin/phpunit -c phpunit.xml
    - vendor/bin/phpunit -c phpunit-integration.xml --testsuite IntegrationTests
